FROM php:8.4-cli

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git curl \
    zip unzip \
    libzip-dev \
    supervisor \
    && docker-php-ext-install pdo_mysql zip opcache pcntl \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 80

CMD ["php", "artisan", "queue:work"]
